remote_theme: pmarsceill/just-the-docs
#theme: "just-the-docs"

repository:            "covidguard/covidguard.github.io"
url:                   https://covidguard.github.io

lang:                  it

# The title of your blog. Used in the sidebar and the browser tab.
title:                 COVID Guard

description:           >
  Lo scopo della pagina è di accrescere la consapevolezza 
  sul covid-19 grazie a semplici grafici

ga_tracking:           UA-161436899-1

keywords:              [COVID coronavirus covid-19 coronavirusitalia data datavisualization]

aux_links:
  "CovidGuard on GitHub":
    - "//github.com/covidguard/covidguard.github.io"
    
defaults:
  -
    scope:
      path: "slides"  #__
    values:
      layout: "iframe"

collections:
  slides:
    output: true