remote_theme: pmarsceill/just-the-docs
#theme: "just-the-docs"

repository:            "covidguard/covidguard.github.io"
url:                   https://covidguard.github.io

lang:                  it

# The title of your blog. Used in the sidebar and the browser tab.
title:                 COVID Guard

description:           >
  Lo scopo della pagina è di accrescere la consapevolezza 
  sul covid-19 grazie a semplici grafici


keywords:              [COVID coronavirus covid-19 coronavirusitalia data datavisualization]